# Name: openke_ms_microforamt
# Purpose: Extracts microformat data (http://microformats.org/) from html pages
#
# Version: 1.0
# History
# 20170405 Initial creation
# 20190501 Updated to opensource project organization
# 20230524 Updated to latest python, minor changes to build process
#
# Build Command: (execute from this current directory)
#     docker build -t="openke_ms_microformat" -f dockerfile  .
#
# RUN:
#     docker run -p EXPOSED_PORT_NUM:8000 openke_ms_microformat
#

FROM python:3.11
RUN pip3.11 install --upgrade pip setuptools wheel

COPY . /root/install/MicroServices
RUN mkdir /opt/microformatParser && \
    mkdir /opt/microformatParser/gunicorn && \
    cp /root/install/MicroServices/*.py /opt/microformatParser/ && \
    cp /root/install/MicroServices/gunicorn/*.conf.py /opt/microformatParser/gunicorn && \
    cp /root/install/MicroServices/requirements.txt /opt/microformatParser/

WORKDIR /opt/microformatParser

RUN pip3.11 install -r requirements.txt

USER 1000

ENTRYPOINT ["/usr/local/bin/gunicorn", "--config", "/opt/microformatParser/gunicorn/gunicorn.conf.py", "--log-config", "/opt/microformatParser/gunicorn/logging.conf.py", "-b", ":8000", "app:app"]
EXPOSE 8000
