# Name: las/collector
# Purpose: Base docker image for java based images
#
# Version: 1.0
# History
# 20170405 Initial creation
#
# Build Command: (executed from current directory)
#     docker build -t="openke_base" Dockerfile_base ../..
#
FROM rockylinux:9.0.20220720
RUN yum update -y
RUN yum -y install java-17-openjdk maven-openjdk17 openssh-clients wget git unzip

# Don't like the following, but java 11 is the default.  This is highly version dependent
RUN alternatives --set java /usr/lib/jvm/java-17-openjdk-17.0.3.0.7-1.el9_0.x86_64/bin/java

COPY . /root/install/OpenKE
WORKDIR /root/install
RUN cd /root/install/OpenKE/externalProjects/crawler4j && \
    mvn install
RUN cd /root/install/OpenKE/externalProjects/boilerpipe && \
    mvn install
RUN cd /root/install/OpenKE/LAS-Common && \
    mvn clean compile dependency:copy-dependencies package install:install
RUN cd /root/install/OpenKE/externalProjects/minIE && \
    mvn clean compile dependency:copy-dependencies package install:install
RUN cd /root/install/OpenKE/LAS-Common-NLP && \
    mvn clean compile dependency:copy-dependencies package install:install
RUN cd /root/install/OpenKE/Collector && \
    mvn dependency:copy-dependencies package install
