# Name: las/collector
# Purpose: Base docker image for java based images
#
# Version: 1.0
# History
# 20170405 Initial creation
#
# Build Command: (executed from current directory)
#     docker build -t="openke_base" Dockerfile_base ../..
#
FROM centos:7.5.1804
RUN yum update -y
RUN yum -y install java maven openssh-clients wget git unzip

COPY . /root/install/OpenKE
WORKDIR /root/install
RUN cd /root/install/OpenKE/externalProjects/crawler4j && \
    mvn install
RUN cd /root/install/OpenKE/externalProjects/boilerpipe && \
    mvn install
RUN cd /root/install/OpenKE/LAS-Common && \
    mvn clean compile dependency:copy-dependencies package install:install
RUN cd /root/install/OpenKE/externalProjects/minIE && \
    mvn clean compile dependency:copy-dependencies package install:install
RUN cd /root/install/OpenKE/LAS-Common-NLP && \
    mvn clean compile dependency:copy-dependencies package install:install
RUN cd /root/install/OpenKE/Collector && \
    mvn dependency:copy-dependencies package install
